### ISSUE TITLE
Compile error after latest changes

### ISSUE THREAD

**Issue by Falconne** [JRoughan/Emanate#2]
Getting these errors after the Jan update:

`Input\IBuildMonitor.cs(23, 33): error CS0840: 'Emanate.Core.Input.BuildKey.ProjectId.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors.
Input\IBuildMonitor.cs(24, 33): error CS0840: 'Emanate.Core.Input.BuildKey.BuildId.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors.`

**Comment by JRoughan** [comment]
Fixed this by moving the web functionality (intended for vNext) back into it's own branch and reset master to the last untarnished commit. This was an unthinkable forced push sorry :) vNext will be worth it but is taking longer than anticipated.
