### ISSUE TITLE
Can't get pre-release version of Serilog from NuGet

### ISSUE THREAD

**Issue by Falconne** [JRoughan/Emanate#3]
I'm getting this, even though TeamCity's NuGet step is set to allow pre-release packages:

`Unable to find version '2.0.0-rc-556' of package 'Serilog'.`

I see that this has now been released anyway, as 2.0.0. Can you update to the released package? Then I don't have to investigate what's going on with TeamCity.

**Comment by JRoughan** [comment]
Done :)
